- boring/src/ssl/connector.rs
- hyper-boring/src/lib.rs
If the host is an IPv6 address, the value returned by `Uri::host()` will [include the surrounding brackets](https://github.com/hyperium/http/pull/292). This causes boring to fail to parse the host as an [IP address](https://github.com/cloudflare/boring/blob/5cb8947d7ec6e0c67fa40167940f313b8d6537f8/boring/src/ssl/connector.rs#L342). Eventually, this causes hostname verification to fail. I _assume_ the hostname verification failure is due to the fact that the host will be compared with the `DNSName`s from `SubjectAlternativeName`, instead of the `IPAddress`es ([`set_ip` vs `set_host`](https://github.com/cloudflare/boring/blob/5cb8947d7ec6e0c67fa40167940f313b8d6537f8/boring/src/ssl/connector.rs#L341-L342)).
> Ensure the host can be parsed as an IPv6 address.

- boring-sys/Cargo.toml
When this crate is used as a dependency on Windows, boring-sys fails to build because Cargo doesn't include .asm files.
This problem was previously seen in [quiche](https://github.com/cloudflare/quiche/pull/776).
> Include .asm files required for Windows

- boring-sys/src/x509.rs
* 2020-11-09 Document X509V3_add1_i2d and friends.
* 2020-11-09 Re-reformat x509.h.
* 2020-11-11 aarch64: Fix name of gnu property note section
* 2020-11-10 Reformat and convert comments in asn1.h.
* 2020-11-10 Unwind M_ASN1_* macros for primitive types.
* 2020-11-10 Switch M_ASN1_TIME macros within the library.
* 2020-11-11 Remove the legacy MSTRING M_ASN1 macros.
* 2020-11-10 Rearrange ASN1_STRING_copy slightly.
* 2020-11-09 Document some defaults for the EVP RSA interface.
* 2020-11-10 Document the basic ASN1_STRING functions.
* 2020-11-10 Remove some unnecessary pointer casts.
* 2020-09-04 Add APIs for checking ASN.1 INTEGERs.
* 2020-11-11 Const-correct and document more X509 functions.
* 2020-11-13 Fix NETSCAPE_SPKI_get_pubkey documentation.
* 2020-11-18 Always check the TLS 1.3 …
> Update boringssl submodule pointer

- boring/src/ssl/mod.rs
There were some specific features I wanted to use on BoringSSL, this PR includes some I have implemented already. 
I have gone with specifiying consts for `SslSignatureAlgorithm` instead of allowing a slice of `u16` just for clarity.
> Enable various client features of bssl

- boring/src/error.rs
- boring/src/ssl/error.rs
We also omit file and line in `ErrorStack` itself now too.
`ErrorStack` is the wrapped error type returned by `hyper_boring::HttpsConnector::call`.
> Tweak yet again the boring error reporting

- boring-sys/src/lib.rs
We don't have any way of fixing these, and it's not feasible to switch away from bindgen.
Ignore the warnings for now.
> Ignore bindgen warnings until they're fixed upstream

- README.md
- boring-sys/build.rs
Following this [issue](https://github.com/cloudflare/boring/issues/36).
> Allow pre-built binaries of BoringSSL

- boring-sys/build.rs
Example output:
```
$ cargo check
Compiling boring-sys v1.1.1 (/home/jnelson/src/boring/boring-sys)
warning: fetching boringssl git submodule
Finished dev [unoptimized + debuginfo] target(s) in 28.27s
```
Fixes https://github.com/cloudflare/boring/issues/3, closes https://github.com/cloudflare/boring/pull/41.
> Fetch git submodule automatically

- tokio-boring/Cargo.toml
- tokio-boring/README.md
- tokio-boring/examples/simple-async.rs
- tokio-boring/src/lib.rs
This also adds an `examples/` directory, to make sure the example in the readme doesn't get out of
date.
Fixes https://github.com/cloudflare/boring/issues/27.
> Update documentation for tokio-boring

- boring-sys/Cargo.toml
`bindgen`'s default features include dependencies like `clap` and
`env_logger` which are unnecessary when building `boring-sys`. When
using tools like `cargo-deny` to audit dependencies with mismatched
versions, these dependencies can easily conflict with application
dependencies.
This change disables `bindgen`'s default features to avoid unnecessary
dependencies.
> boring-sys: Disable unnecessary bindgen dependencies

- tokio-boring/src/lib.rs
`tokio_boring::HandshakeError` currently requires that the inner stream
implements `Debug` for its `Display` implementation. This constraint is
unnecessary.
This change removes this `Debug` constraint so `HandshakeError` always
implements `Display`.
> Relax constraints on `Display for tokio-boring::HandshakeError`

- boring-sys/src/lib.rs
I have removed the PasswordCallback. References to this are not present in the repository, but is it ok to delete this directly or should this be marked as `#[deprecated]` first?
Best regards
Robin
> Remove PasswordCallback from boring-sys

- CHANGELOG.md
- boring-sys/CHANGELOG.md
- boring-sys/Cargo.toml
- boring/Cargo.toml
- hyper-boring/CHANGELOG.md
- hyper-boring/Cargo.toml
- tokio-boring/CHANGELOG.md
- tokio-boring/Cargo.toml
Closes https://github.com/cloudflare/boring/issues/54
- Major version for boring-sys: `PasswordCallback` was removed
- Major version for boring: the public `*Ref` types were removed and `foreign-types` appears in our public api and had a major version bump
- Patch version for tokio-boring: the only API change was removing the `S: Debug` bound
- Patch version for hyper-boring: no API changes, only removed dependencies
> Bump versions for release

- boring/src/pkey.rs
I'm not quite sure why these are unsafe traits, probably to prevent implementing them for random types accidentally. However, Clippy demands a `# Safety` section in their docs. Tell it to get lost.
> Suppress Clippy warnings about missing safety docs

- boring/src/bn.rs
Wrap `BN_bn2bin_padded()` which comes useful for exporting fixed-length BIGNUMs, more efficient than padding result of `to_vec()` afterwards.
Note that in OpenSSL the function is called `BN_bn2binpad()` and has a different order of arguments. BoringSSL's BN_bn2bin_padded() also takes the desired length as `size_t`.
> boring: `BigNumRef::to_vec_padded()`

- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
Latest release of `quiche` (`0.12.0`) [uses boringssl commit: `f1c7534`](https://github.com/cloudflare/quiche/tree/0.12.0/quiche/deps).
This breaks case where one wants to make `quiche` and `boring` rely on the same `quichessl` implementation (via setting `BORING_BSSL_PATH` env var).
```
┌───────────┐
┌─────┤ User Code ├──────┐
│     └───────────┘      │
│                        │
▼                   ┌────▼────┐
┌────────┐              │ boring  │ 
│ Quiche │              └────┬────┘
└───┬────┘                   │
│                   ┌────▼─────┐
│                   │boring-sys│
│                   └────┬─────┘
│     ┌───────────┐      │
└─────► boringssl │◄─────┘
└───────────┘
```
That's because of some changes in the public interface of `boringssl`.
In particular,
- …
> Update boringssl deps for quiche 0.12.0 compatibility

- .github/workflows/ci.yml
- boring-sys/build.rs
There was some prior work for iOS support, but it did not really produce a successful build because running `bindgen` failed on macOS (#22). That's because bindgen tried using macOS headers instead of iOS ones, and those don't really match. Proper `-isysroot` flag needs to be passed to clang invocations made by bindgen, pointing it into the right direction.
- Fix building for all iOS targets that rustc supports:
- `aarch64-apple-ios` – iOS devices running ARM64
- `aarch64-apple-ios-sim` – iOS simulator running on Apple M1
- `x86_64-apple-ios` – iOS simulator running on x86_64
- Teach CI to test building for aforementioned targets
-  Only `cargo build`, no `cargo test`, since that's *way* more involved.
- Suppress some Clippy warnings so that the build gets green
I don't have M1 hardware …
> Support cross-compilation for iOS

- boring-sys/Cargo.toml
- boring-sys/src/lib.rs
Notably this release provided a fix for https://github.com/rust-lang/rust-bindgen/issues/1651
> chore: update to bindgen 0.60

- boring-sys/build.rs
The MSVC generator hack should be only applied to MSVC ABI, thereby making MinGW-w64 toolchain functional.
Related to https://github.com/cloudflare/boring/pull/76
> MSVC generator hack should be only applied to MSVC

- boring-sys/build.rs
Things kinda work without it on Linux if you have `gcc-multilib` installed, but that's just getting lucky. We compile against the Android sysroot; we should use it for bindgen as well.
> boring-sys: Use the Android NDK sysroot when running bindgen

- boring-sys/build.rs
- boring-sys/src/lib.rs
- boring/src/aes.rs
- boring/src/sha.rs
- boring/src/ssl/bio.rs
- boring/src/ssl/connector.rs
- boring/src/ssl/mod.rs
- boring/src/stack.rs
- boring/src/string.rs
According to [the docs](https://doc.rust-lang.org/stable/std/mem/fn.uninitialized.html),
> Calling this when the content is not yet fully initialized causes immediate undefined behavior.
> it [is] undefined behavior to have uninitialized data in a variable even if that variable has an integer type.
Using MaybeUninit instead, as recommended by the official documentation, avoids undefined behavior by not creating a `&mut` reference to uninitialized data.
This also fixes some harmless clippy warnings.
> Remove uses of `mem::uninitialized`

- boring-sys/build.rs
- boring-sys/cmake/aarch64-linux.cmake
`boring`'s cross-compilation support isn't in a great state due to how manually CMake wants to be configured, but this enables at least basic cross-compilation in two cases Signal cares about:
- Cross-compiling to AArch64 Linux can be done with a CMake toolchain file, along with setting the correct compiler and include paths in the environment (`CC`, `CXX`, `CPATH`). This is similar to how cross-compiling to x86 works.
- Cross-compiling from X64 Windows to ARM64 Windows doesn't look at the toolchain at all, because CMake + Visual Studio can already cross-compile. Unfortunately, the Visual Studio CMake generator doesn't set `CMAKE_SYSTEM_PROCESSOR`, which is what the BoringSSL CMakeLists.txt is looking at to choose the architecture. For now, disable the use of assembly when cross-compiling …
> Add minimal cross-compilation support for Windows and AArch64 Linux

- .github/workflows/ci.yml
- README.md
- boring-sys/build.rs
- boring/examples/mk_certs.rs
- boring/src/pkey.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- boring/src/x509/mod.rs
Signed-off-by: Piotr Sikora <piotr@aviatrix.com>
> Update BoringCrypto to FIPS 140-2 certificate 4407.

- boring/src/bio.rs
- boring/src/ssl/mod.rs
- boring/src/x509/mod.rs
- boring/src/x509/store.rs
- boring/src/x509/tests.rs
Notable commits that cause code changes here:
X509 fields notBefore and notAfter need to be specified
https://boringssl-review.googlesource.com/c/boringssl/+/49349
X509ReqBuilder only accepts X509v1 now
https://boringssl-review.googlesource.com/c/boringssl/+/52605
Some functions switched from int to size_t
https://boringssl-review.googlesource.com/c/boringssl/+/54985
CECPQ2 support was dropped
https://boringssl-review.googlesource.com/c/boringssl/+/58645
This is a breaking change.
> Update boringssl to latest upstream commit (fixes #100)

- boring/src/derive.rs
It looks like there's a missing `Drop` implementation for `Deriver`. There's a `EVP_PKEY_CTX_new` but no corresponding call to `EVP_PKEY_CTX_free`.
> boring: Fix memory leak in `Deriver`

- boring/src/asn1.rs
- boring/src/x509/extension.rs
- boring/src/x509/mod.rs
- boring/src/x509/tests.rs
> Port security fixes from the openssl crate (fixes #111)

- boring/src/x509/mod.rs
- boring/src/x509/store.rs
This reverts commit 1c1af4b38b65aaed08efe1db45b40abd0bf9ed78, reversing changes made to da32be1fa9d6c45a1a1b16bfeffe27bfa9344b28.
SslContextBuilder::cert_store_mut returns a &mut X509StoreBuilder backed by a X509Store that is already shared with an existing SslContext.
> Revert "Merge pull request #108 from nox/store-clone"

- boring-sys/build.rs
This longer path (inside the prebuilt toolchain included in the NDK) has been the preferred sysroot since NDK r19. Newer NDKs no longer have a top-level "sysroot" directory at all.
Follow-up to #82, my bad for testing against an older NDK at that time.
> boring-sys: Update Android NDK sysroot path

- Cargo.toml
- boring-sys/Cargo.toml
- boring-sys/build.rs
- boring-sys/scripts/apply_pq_patch.sh
- boring-sys/scripts/apply_rpk_patch.sh
Previously we were building from the deps directory with submodules. For publishing we were copying files in sumbodules into the package. With this we were making the package directory dirty with build artifacts and applied patches.
This commit change the build script's behaviour: sources are now copied to the output directory and then boringssl is built from there.
In addition, this commit adds files that were missing from the package for building with patches.
> Fix builds for features that require git patches

- boring-sys/build.rs
This was originally going to be fixed by #101, however that PR was closed and superseded by #117, which was missing this fix.
The original problem was caused by #97, which updated boringssl to a version that included [a change that removed hmac.h from ssl.h](https://github.com/google/boringssl/commit/05b360d797353dd19842aa5a38dbccbf1c867f21).
This PR adds an include for hmac.h, so it is again available through boring-sys.
> Adding hmac.h to included headers

- boring-sys/build.rs
Quick fix: addresses a missing `.trim()` in `boring-sys/build.rs`, which causes builds with the `fips-link-precompiled` feature enabled to fail:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `"bcm.o\n"`,
   right: `"bcm.o"`: failed to verify FIPS module name', /home/mmunoz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-3.0.2/build.rs:560:5
```
> Fix missing .trim() when verifying FIPS module name.

- Cargo.toml
- boring-sys/Cargo.toml
- boring-sys/build.rs
- boring/Cargo.toml
- boring/src/bio.rs
- boring/src/fips.rs
- boring/src/ssl/callbacks.rs
- boring/src/ssl/mod.rs
- boring/src/x509/mod.rs
- boring/src/x509/verify.rs
- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
Make the later compatible with `rpk` feature.
> Separate `fips` and `fips-link-precompiled` features.

- Cargo.toml
This fixes building with `cargo update -Z minimal-versions`
> Fix -Z minimal-versions

- .github/workflows/ci.yml
- boring-sys/Cargo.toml
- boring/Cargo.toml
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
Overwrite boringSSL's default key exchange preferences with safe
defaults using feature flags:
* "kx-client-pq-supported" enables support for PQ key exchange algorithms.
Classical key exchange is still preferred, but will be upgraded to PQ
if requested.
* "kx-client-pq-preferred" enables preference for PQ key exchange,
with fallback to classical key exchange if requested.
* "kx-client-nist-required" disables non-FIPS-compliant algorithms on the client side.
If any of these "kx-*" features are enabled, then don't compile bindings
for `SSL_CTX_set1_curves()`. This is to prevent the feature flags from
silently overriding curve preferences chosen by the user.
Ideally we'd allow both: that is, use "kx-\*" to set defaults, but still
allow the user to manually override them. However, this …
> Use features to set key exchange preferences

- Cargo.toml
- RELEASE_NOTES
- boring-sys/build.rs
This PR is intended to make linking against a pre-compiled, FIPS-validated version of BoringSSL a bit easier and cleaner. It adds a subdir to Cargo's rustc-link-native directories and automatically sets BoringSSL's include path to `${BORING_BSSL_PATH}/include` if `BORING_BSSL_PATH` is set and `BORING_BSSL_INCLUDE_PATH` is not set.
> Tweaks for ergonomic linking

- boring/src/ssl/connector.rs
> Provide into_ssl() for ConnectConfiguration

- boring/src/ssl/mod.rs
While not commonly used, P-521 is a perfectly safe choice of key exchange algorithm.
> Enable P-521 with "kx-safe-default"

- boring/src/ssl/mod.rs
These APIs allow more SslStream to be used more flexibly
> Add new(), connect(), accept() and handshake() to SslStream

- Cargo.toml
I don't think anything else needs to be updated.
Changelog is here: https://github.com/rust-lang/rust-bindgen/blob/main/CHANGELOG.md#0681
> deps: update to bindgen 0.68

- boring/src/fips.rs
In boringssl, FIPS_mode_set is more or less useless, and it doesn't even set an error stack at all on failure, so there is no point using it instead of FIPS_mode.
> Remove boring::fips::enable (fixes #150)

- boring/examples/mk_certs.rs
- boring/src/ssl/error.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- boring/src/x509/mod.rs
- boring/src/x509/tests.rs
Instead of making it a `c_int` wrapper with an `OK` variant, we make it a type alias for `Result<(), X509VerifyError>`, where
`X509VerifyError` only represents failures. This is a breaking change.
We also write bindings for all the existing verify error codes.
> Improve X509VerifyResult

- boring-sys/Cargo.toml
- boring-sys/build/config.rs
- boring-sys/build/main.rs
- boring/Cargo.toml
- boring/src/lib.rs
- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
BoringSSL checkouts for FIPS-validated builds and for normal builds can be quite different, enough for them to not build with their expected `fips` or `fips-link-precompiled` feature settings, for example when they are both used as runtime dependencies and build dependencies. When using cargo's resolver 2, the user then needs to make sure that boring is compiled with the same FIPS-related features for both kind of dependencies, which can sometimes be difficult.
For this reason, this PR introduces a new set of variables prefixed by `BORING_BSSL_FIPS_` instead of `BORING_BSSL_`:
* `BORING_BSSL_FIPS_PATH`
* `BORING_BSSL_FIPS_INCLUDE_PATH`
* `BORING_BSSL_FIPS_SOURCE_PATH`
* `BORING_BSSL_FIPS_PRECOMPILED_BCM_O`
While at it, the prefix were normalized, as `BORING_BSSL_FIPS_PRECOMPILED_BCM_O` …
> Introduce a new set of env variables specific to FIPS builds

- boring-sys/Cargo.toml
- boring-sys/build/config.rs
- boring-sys/build/main.rs
- boring/Cargo.toml
- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
This removes `rpk` from tokio-boring and hyper-boring, and replaces feature `no-patches` with env variable `BORING_BSSL{,_FIPS}_ASSUME_PATCHED`, see individual commits for rationale.
> Rework rpk and no-patches features

- boring/src/ssl/callbacks.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- boring/src/ssl/test/private_key_method.rs
- boring/src/ssl/test/server.rs
- boring/src/ssl/test/session.rs
- tokio-boring/src/async_callbacks.rs
- tokio-boring/src/lib.rs
- tokio-boring/tests/async_get_session.rs
- tokio-boring/tests/common/mod.rs
The signature of the sync callback required a breaking change.
> Introduce set_async_get_session_callback

- Cargo.toml
- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
This was an accidental regression in
d1ee9bfd868a472a04f92e15e011d0fc42db6b88 which leads to pulling in the full featureset of tokio and hyper for all dependents of tokio-boring and hyper-boring.
Fixes #179.
> hyper and tokio "full" feature for dev builds only

- tokio-boring/src/async_callbacks.rs
- tokio-boring/src/lib.rs
- tokio-boring/src/mut_only.rs
They are unnecessary as we ever only retrieve the futures from ex data to poll them, thus when we have mutable access to them, so Send is all we need.
> Remove Sync trait bounds on callback futures

- boring/src/ssl/mod.rs
- tokio-boring/src/async_callbacks.rs
Setting callbacks multiple times on a SslContextBuilder causes the previous callback installed to leak, using replace_ex_data internally prevents that.
We also start using it in tokio-boring in with_ex_data_future, my understanding is that the futures currently in use are never installed twice by that function but that could change in the future with the addition of more async callbacks.
> Use replace_ex_data more

- .github/workflows/ci.yml
- boring-sys/build/config.rs
- boring-sys/build/main.rs
We noticed that the CI matrix wasn’t always building for the Rust target it intended, leading to surprise breakage (e.g. #187) when doing release builds. This addresses that in a few ways:
1. add `--target` to `cargo test`
2. `check_only` flag
- skip running tests for non-native architectures and targets; instead do `cargo build … --tests` to confirm cross-compilation
3. various customization options
- specific packages required to cross-compile for the target, environment variables, etc.  
4. last resort: drop a target
- musl doesn’t have a standard C++ setup to use
> Update CI to build for all matrix targets

- boring/src/bio.rs
- boring/src/ssl/mod.rs
- boring/src/x509/mod.rs
This feature expects a recent boringssl checkout (such as the one found in boring-sys/deps/boringssl), so it should not be using the same bindings as the fips feature, which are based on boring-sys/deps/boringssl-fips, which is older and with a different API.
> Fix support for fips-link-precompiled

- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
Expose APIs to access `SSL_CTX_set_compliance_policy` and `SSL_CTX_get_ciphers`.
> Expose `set_compliance_policy` and `get_ciphers`

- boring-sys/build/config.rs
- boring-sys/build/main.rs
- boring-sys/patches/rpk.patch
We need to add `/build/crypto` and `/build/ssl` to the library search path to handle the case where we pass `BORING_BSSL_SOURCE_PATH` when building without enabling any fips features. Otherwise, non bazel commits will not work because `/build/` itself will not contain any crypto libraries to link with
> Fix building with non bazel commits of boringssl

- boring-sys/build/main.rs
When passing BORING_BSSL_FIPS_PATH, you need to add /lib/ to the search path, and when passing BORING_BSSL_PATH you need to add /crypto/ and /ssl/ to the search path.
> Fix building with BORING_BSSL_PATH / BORING_BSSL_FIPS_PATH

- boring/src/ssl/mod.rs
- tokio-boring/src/lib.rs
openssl recently introduced `read_uninit` and `write_uninit` in [0.10.61](https://github.com/sfackler/rust-openssl/compare/openssl-v0.10.60...openssl-v0.10.61) and it is used in tokio-openssl [0.6.4](https://github.com/tokio-rs/tokio-openssl/pull/47/files) as a means of making buffer initialization sound. This pr is a combination of both of those changes.
> Introduce and use read_uninit and write_uninit duplicated from openssl

- boring-sys/build/main.rs
Warnings of layout tests were already fixed in bindgen 0.60: https://github.com/rust-lang/rust-bindgen/issues/1651.
> Enable layout tests on iOS target

- boring/src/ssl/mod.rs
While setting curves should be restricted by the kx-safe-default feature, reading the curve is allowed.
> Remove kx-safe-default gate on SslCurve

- hyper-boring/src/cache.rs
- hyper-boring/src/lib.rs
When establishing new TLS sessions, servers may send multiple session tickets (RFC8446 4.6.1). hyper-boring caches tickets without placing a limit on how many tickets are cached. This leads to unbounded growth of hyper-boring's cache and leaves clients vulnerable to malicious servers who might send many session tickets to exhaust a client's available memory.
This change bounds the cache to a default of 8 tickets.
> bound session cache

- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
The popular [`dependency-review-action`](https://github.com/actions/dependency-review-action) requires the license field be in valid SPDX format. (We are hitting false positives on this dependency via `dependency-review-action` over at [Teleport](https://github.com/gravitational/teleport)).
> Updates license field to valid SPDX format

- boring-sys/patches/boring-pq.patch
- boring/src/lib.rs
- boring/src/ssl/mod.rs
Fix three potential timing sidechannels. These don't affect ephemeral usage of Kyber as in TLS, but it's good practice to get rid of them anyway.
Also adds IPDWing, a preliminary version of X-Wing using the initial public draft (IPD) of ML-KEM. Don't use it.
> PQ: fix timing sidechannels and add IPDWing

- .github/workflows/ci.yml
See https://github.com/Homebrew/homebrew-core/issues/173191 and https://github.com/actions/runner-images/issues/9966
> (ci): Fix macos crossbuild action by forcing brew link w python@3.11

- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
While testing I noticed that `SslRef::curve()` was returning `29` (SSL_CURVE_X25519) instead of `948` (NID_X25519).
I assume most users rely on `SslCurve::name()` which is correct because it's passing the id back to the ffi layer.
> Fix SSL curve identifiers

- boring/src/x509/mod.rs
The [x509_check_host docs](https://commondatastorage.googleapis.com/chromium-boringssl-docs/x509.h.html#X509_check_host) state:
> X509_check_host checks if x509 matches the DNS name chk. It returns one on match, zero on mismatch, or a negative number on error. 
The current implementation will return `true` for 1, -1, and -2, therefore returning an incorrect value if any of the above error cases are [hit](https://github.com/google/boringssl/blob/44b3df6f03d85c901767250329c571db405122d5/src/crypto/x509v3/v3_utl.c#L1036-L1045).
> Fix x509_check_host return value

- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
We previously added an `SslCurveId` struct to house SSL_CURVE variants of the internal NID constants, to allow `SslRef::curve()` to properly instantiate `SslCurve` structures. This was done to ensure `SslRef::set_curves()` did not break, as it expects the internal NID constants instead of the public SSL_CURVE ones. In future versions of boringssl, this problem is solved by virtue of the SSL_CTX_set1_group_ids API. Since we don't have this yet, this commit adds `SslCurve::nid()` so `SslRef::set_curves()` can convert the SSL_CURVE constants to the internal NID representation internally without breaking the public API.
> Add SslCurve::to_nid() and remove SslCurveId

- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
Closes https://github.com/cloudflare/boring/issues/257
> Properly handle `Option<i32>` in `SslRef::set_curves`

- .github/workflows/ci.yml
- Cargo.toml
- boring/Cargo.toml
- boring/src/ssl/mod.rs
- boring/src/util.rs
- boring/src/x509/mod.rs
- boring/src/x509/tests/mod.rs
`ForeignTypeExt` and `ForeignTypeRefExt` are inspired by https://github.com/sfackler/rust-openssl/pull/1345, which make dealing with FFI safer and more ergonomic. The new APIs also allow for gracefully handling instances where the initial API call results in `NULL`
> Expose mTLS related APIs, introduce ForeignTypeExt + ForeignTypeRefExt, add corresponds macro

- boring/src/ssl/mod.rs
set_surves_list is similar to set_curves, but the curves are specified by a string. This makes it convenient when the supported curves of the underlying BoringSSL is not known at compile time.
Also fix a bug in checking return value of SSL_set1_curves_list.
> Expose SSL(_CTX)_set1_curves_list

- Cargo.toml
bindgen has had a lot of improvements since 0.68, and this newer version seems to able to compile libbssl from within edgeworker
> Update bindgen to 0.70.1

- boring-sys/patches/boring-pq.patch
- boring/src/lib.rs
- boring/src/ssl/mod.rs
Builds on PR #269.
[X25519MLKEM768](https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/02/) is the successor of [X25519Kyber768Draft00](https://datatracker.ietf.org/doc/draft-tls-westerbaan-xyber768d00/) now that NIST has released [ML-KEM](https://csrc.nist.gov/pubs/fips/203/ipd).
IANA has assigned the [codepoint `0x11ec`](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8).
Upstream BoringSSL support landed in [this commit](https://github.com/google/boringssl/commit/7fb4d3da5082225c7180267e9daad291887ce982). The version of BoringSSL we patch does not include it, so we add it manually.
Chrome and Firefox are planning to enable in October.
This PR is based on the [IPD-Wing PR](https://github.com/cloudflare/boring/pull/243). There are two …
> Add post-quantum key agreement X25519MLKEM768

- boring/src/ssl/mod.rs
There are users of the `kx-*` features that don't use the PQ patch. Those would break with an older version of BoringSSL.
> Don't enable support for X25519MLKEM768 by default (yet)

- boring-sys/patches/boring-pq.patch
crypto_test_data.cc is not included anymore since 2475ef386bd6158151f5ad5c4cf697d02ceca2b0
> boring-pq.patch Fix by not updating crypto_test_data.cc

- boring-sys/build/main.rs
With the bindgen 0.70 upgrade, the default rust target is set to be 1.77, which becomes the de facto MSRV of boring-sys since the change.
This change makes sure that the MSRV of boring-sys is kept at 1.70, which is the same as that of bindgen.
> Set MSRV to 1.70

- boring/src/ssl/callbacks.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/cert_verify.rs
- boring/src/ssl/test/mod.rs
Add a wrapper for `SSL_CTX_set_cert_verify`, which allows consumers to override the default certificate verification behavior.
The binding resembles `SSL_CTX_set_verify`'s.
See
https://docs.openssl.org/master/man3/SSL_CTX_set_cert_verify_callback/ for more details.
> Add `set_cert_verify_callback` (`SSL_CTX_set_cert_verify`)

- boring-sys/build/main.rs
Only with this does it work for us. This is basically a redux of #223 that should be closed as it is now outdated. It should close #242.
> Fix Windows build

- boring/src/aes.rs
- boring/src/asn1.rs
- boring/src/base64.rs
- boring/src/bn.rs
- boring/src/ssl/test/custom_verify.rs
- boring/src/x509/mod.rs
- boring/src/x509/store.rs
- boring/src/x509/verify.rs
I've copied rust-openssl APIs that are needed to make c2pa.org SDK compatible with boring (jira IMAGES-1371).
The openssl crate had also a couple of important safety fixes — `X509VerifyParam::set_host` with 0-len host was unsafe, and `X509StoreRef::objects` references may get invalidated by other accesses of the shared cache. 
`X509StoreRef::objects` is unfixable, so I've marked it as `unsafe` and deprecated, which is technically semver-breaking, but I think the risk of use-after-free in a safe API could warrant releasing it in 4.x despite breakage.
> x509 verify params + safety fixes

- Cargo.toml
- hyper-boring/Cargo.toml
- hyper-boring/src/v1.rs
- hyper-boring/tests/v1.rs
Closes #295. Should probably follow after #304. Requires breaking changes as well.
> Refactor!: Remove strict `TokioIo` response requirement from `hyper_boring::v1::HttpsConnector`

- .github/workflows/ci.yml
- Cargo.toml
- hyper-boring/Cargo.toml
- hyper-boring/src/lib.rs
- hyper-boring/src/v0.rs
- hyper-boring/src/v1.rs
- hyper-boring/tests/v0.rs
- hyper-boring/tests/v1.rs
Closes #294. Requires breaking changes, but only regarding the `hyper1` feature's enabled module path; the default v0 is still preserved. What is proposed here in order to achieve the objective is to have both modules be re-exported when the other feature is not enabled, and have them be made public when both features are enabled at the same time. This way, the features should be kept additive: all four combinations are supported. It enables dependency de-duplication when consuming it.
> Refactor!: Introduce a Cargo feature for optional Hyper 0 support

- boring-sys/build/config.rs
- boring-sys/build/main.rs
- boring/src/x509/tests/trusted_first.rs
* Support linking with a runtime cpp library
> As of https://boringssl-review.googlesource.com/c/boringssl/+/66288,
libssl allows a C++ runtime dependency. As such, we need to link with a
cpp runtime library. Implementation is inspired heavily from
https://github.com/google/boringssl/commit/54c956b2e668e11c75f1ee0367f1b3a0ad28eff9. Before releasing this change, we'll need to figure out a way to support
this for windows.
* Fix bug with accessing memzero'd X509StoreContext in tests
> As of https://boringssl-review.googlesource.com/c/boringssl/+/64141,
X509_STORE_CTX_cleanup will zero the memory allocated to the
X509_STORE_CTX. Because X509StoreContextRef::init invokes
X509_STORE_CTX_cleanup once the with_context closure has finished,
calling X509StoreContextRef::verify_result (or any API …
> Prepare for syncing with upstream

- boring/src/ssl/error.rs
Mid-handshake errors that occur before certificate verification currently look like this:
```
TLS handshake failed: cert verification failed - Invalid certificate verification context [WRONG_VERSION_NUMBER]
```
Despite no certificate even being received yet, the error complains about a failed verification. The cause here is that `cert verification failed` is only omitted if the verification result is `OK`. The default in BoringSSL before verification runs is `INVALID_CALL`, however.
`INVALID_CALL` is set/returned in these places:
- https://github.com/google/boringssl/blob/44b3df6f03d85c901767250329c571db405122d5/src/ssl/internal.h#L3904
- https://github.com/google/boringssl/blob/44b3df6f03d85c901767250329c571db405122d5/src/ssl/ssl_session.cc#L396
- …
> Remove INVALID_CALL from mid-handshake error message

- boring/src/ssl/mod.rs
X25519MLKEM768 is the standardised successor of the preliminary X25519Kyber768Draft00. Latest browsers have switched to X25519MLKEM768. Cloudflare supports both on the edge.
We've had support for X25519MLKEM768 in this crate for a while, but didn't enable by default. We're now enabling serverside support by default. We also let clients advertise support when set to kx-client-pq-supported.
We don't enable support by default yet for clients set to kx-client-pq-preferred, as that would cause an extra round-trip due to HelloRetryRequest if the server doesn't support X25519MLKEM768 yet.
BoringSSL against which we build must support X25519MLKEM768, otherwise this will fail.
> RTG-3333 Support X25519MLKEM768 by default, but don't sent it as client

- boring/src/error.rs
There are only constants for lib-specific reasons, so library_code + reason_code must be checked instead of combined code.
> Detailed error codes

- boring-sys/src/lib.rs
We don't need the workaround that was initially introduced for a bug in openssl, and OPENSSL_init_ssl always calls into CRYPTO_library_init on boringssl, so just call it explicitly.
> Clean up boring_sys::init()

- boring-sys/Cargo.toml
Compiling i686-unknown-linux-musl and other 32-bit Linux platforms reported an error because the publish crate did not include the file. Compiling normally after completing the file
tracing line: https://github.com/cloudflare/boring/blob/bf0e21cec8f7bfd95996d4112cd4a5a36620682e/boring-sys/build/main.rs#L298
```log
error: failed to run custom build command for `boring-sys v4.13.0`
Caused by:
process didn't exit successfully: `/home/rust/src/target/release/build/boring-sys-c4cc99b1cc4d49f5/build-script-main` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=BORING_BSSL_PATH_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=BORING_BSSL_PATH_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=TARGET_BORING_BSSL_PATH
cargo:rerun-if-env-changed=BORING_BSSL_PATH …
```
> build: Fix the build for 32-bit Linux platform

- boring-sys/build/main.rs
cmake-rs' jobserver doesn't work reliably, if at all. One workaround is to set CMAKE_BUILD_PARALLEL_LEVEL to num_cpus. On my machine it makes builds over 3x faster
> Set CMAKE_BUILD_PARALLEL_LEVEL to num_cpus

- Cargo.toml
- boring-sys/build/main.rs
There's a bug on OSX that prevents the CMake jobserver from working properly, and so CMake defaults to a single-threaded build. It's not clear when this is actually going to get fixed, so recent versions of cmake-rs just disable the jobserver and have CMake fall back to the number of available cores:
https://github.com/rust-lang/cmake-rs/pull/229
This means we don't need e6833b0074086422b065edec2839ec9800c73885
> Bump cmake-rs to improve Mac OS build parallelism

- boring/src/ssl/ech.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/ech.rs
Previously, set_ech_keys would consume the SslEchKeys struct to enforce the requirement that the struct is immutable after initializing it on a SSL_CTX. The problem with this is that it requires applications to needlessly reallocate the SslEchKeys struct if they want to initialize keys on multiple SSL_CTXs, which is a pretty common pattern. To work around this, we introduce a builder (SslEchKeysBuilder) that requires mutable access to add keys to the underlying struct. set_ech_keys takes in a reference to SslEchKeys, which can only be made via consuming the builder.
> Introduce a builder pattern for SslEchKeys + make set_ech_keys take a reference

- Cargo.toml
- boring-sys/build/main.rs
Some users of boring have issues with newer versions of cmake. Because we have an alternative solution, we can hold off on the bump for now.
> Revert cmake bump (for now) as it is overly restrictive

- boring/src/ssl/mod.rs
See https://github.com/sfackler/rust-openssl/pull/2360 and https://nvd.nist.gov/vuln/detail/CVE-2025-24898. From the rust-openssl PR:
<blockquote>
`SSL_select_next_proto` can return a pointer into either the client or server buffers, but the type signature of the function previously only bound the output buffer to the client buffer. This can result in a UAF in situations where the server slice does not point to a long-lived allocation.
Thanks to Matt Mastracci for reporting this issue.
</blockquote>
> Fix lifetimes in ssl::select_next_proto

- RELEASE_NOTES
v4.15.0 was tagged a few days ago but wasn't released until today, where a new commit made it to master and snuck into the publish. I updated the v4.15.0 tag to point to the right commit hash as well.
> Add missing release notes entry

- .github/workflows/ci.yml
GitHub has [removed](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down) the actions/cache@v1 and actions/cache@v2 actions as of March 1st. CI runs after March 1st will now fail, as seen [here](https://github.com/signalapp/boring/actions/runs/13734955858/job/38417497855?pr=33). 
To fix CI, this just drops in the latest actions/cache@v4 in place of the existing actions/cache@v1. I ran a test of it against our fork and it passed [here](https://github.com/signalapp/boring/actions/runs/13768046827).
> Update to actions/cache@v4

- boring-sys/build/main.rs
- boring/Cargo.toml
- boring/src/fips.rs
- boring/src/lib.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
As of boringSSL commit a430310d6563c0734ddafca7731570dfb683dc19, we no
longer need to make exceptions for the types of BufLen, ProtosLen, and
ValueLen, which means the "fips-compat" feature is no longer needed for
"fips" users.
Currently "fips" implies "fips-compat". To allow users to upgrade
without breaking API compatibility with boring version 4, add a new
feature, "fips-no-compat", that does not imply "fips-compat".
In boring 5, we should remove "fips-no-compat" and decouple
"fips-compat" from "fips".
> Add feature "fips-no-compat"

- .github/workflows/ci.yml
- boring-sys/build/main.rs
- boring/Cargo.toml
- boring/src/fips.rs
- boring/src/lib.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
Based on #332 (merge that first).
Partially addresses #196.
NOTE: This is an API breaking change.
Modify the "fips" feature so that it no longer implies "fips-compat".
The latter is no longer needed for recent builds of boringSSL; users who
need older builds will need to enable "fips-compat" explicitly.
Also, remove the "fipps-no-compat" feature, as it's now equivalent to
"fips".
> Remove "fips-no-compat", decouple "fips-compat" from "fips"

- boring-sys/build/config.rs
- boring/src/ssl/mod.rs
Internal users often have two builds for `boring`, one using a precompiled build of boringSSL and another built from source with patches applied. However the features that enable these builds are mutually exclusive. For example, the `"pq-experimental"` feature is required to build the source with all of the necessary codepoints for PQ key exchange, but if this feature is enabled and a precompiled boringSSL is provided, then the build will fail. This means users will have to also control their builds with mutually exclusive features.
An alternative is to *ignore* features that enable patches whenever a precompiled boringSSL is provided. This is a little different from the "assume patched" environment variable, which applies whenever we're building from source.
> boring-sys: Ignore patches when boringSSL is precompiled

- .github/workflows/ci.yml
- boring-sys/build/main.rs
- boring/Cargo.toml
- boring/src/fips.rs
- boring/src/lib.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
This reverts commit 57307d739e0699454effccc0dd3015287fab398e.
This is a breaking change, so we'll land it when we're ready to cut 5.0.
> Revert "Remove "fips-no-compat", decouple "fips-compat" from "fips""

- boring/src/lib.rs
This was added in #264, but not documented so far.
> Document linking to C++ standard library

- boring-sys/Cargo.toml
- boring-sys/build/config.rs
- boring-sys/build/main.rs
- boring/Cargo.toml
- boring/src/fips.rs
- boring/src/lib.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- hyper-boring/Cargo.toml
- tokio-boring/Cargo.toml
Newer versions of FIPS don't need any special casing in our bindings,
unlike the submoduled boringssl-fips. In addition, many users currently
use FIPS by precompiling BoringSSL with the proper build tools and
passing that in to the bindings.
Until we adopt the Update Stream pattern for FIPS, there are two main
use cases:
1. Passing an unmodified, precompiled FIPS validated version of
boringssl (fips-precompiled)
2. Passing a custom source directory of boringssl meant to be linked
with a FIPS validated bcm.o. This is mainly useful if you carry
custom patches but still want to use a FIPS validated BoringCrypto.
(fips-link-precompiled)
This commit introduces the `fips-precompiled` feature and removes the
`fips-no-compat` feature.
> Add fips-precompiled feature to support newer versions of FIPS

- boring-sys/Cargo.toml
- boring/src/x509/store.rs
Some scenarios require repeatedly creating TLS connectors. We aim to reuse X509Store instead of recreating it each time. Implementing Clone could be a good solution.
> feat(x509): Implement `Clone` for `X509Store`

- boring/src/ssl/test/cert_verify.rs
- boring/src/ssl/test/server.rs
- boring/src/x509/mod.rs
This method reliably retrieves the certificate the `X509_STORE_CTX` is verifying, unlike `X509_STORE_CTX_get_current_cert`, which may return the "problematic" cert when verification fails.
> Add `X509_STORE_CTX_get0_cert` interface

- boring/src/lib.rs
- boring/src/ssl/mod.rs
- boring/src/x509/mod.rs
- boring/src/x509/tests/mod.rs
We introduce `X509StoreContextRef::init_without_cleanup`.
Function `X509_STORE_CTX_init` requires its arguments to outlive the store context, which is why `X509StoreContextRef::init` takes a closure which is guaranteed to be followed by a call to `X509_STORE_CTX_cleanup`.
We can avoid that by using the store context's ex data to store and own the arguments that were passed to `X509_STORE_CTX_init`.
> Improve X509StoreContext initialization API

- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- boring/src/x509/store.rs
> Make X509Store shareable between contexts

- boring/src/ssl/mod.rs
**Description**
- Exposes BoringSSL method `SslRef::set_groups` -> `SSL_set1_groups` to directly set curve groups against an ongoing SSL session. This is necessary because in boringssl, calling `SSL_set_SSL_CTX` to switch the `SSL_CTX` does not update the supported group list (supported_group_list) on the existing SSL session object. We must set the curve list directly on the session after the SSL object is created but before the handshake begins.
- `SSL_set1_groups` is more efficient than the currently exposed `SslRef::set_curves_list` -> `SSL_set1_groups_list` which uses more complicated parsing logic to [parse colon delimited](https://github.com/google/boringssl/blob/bf4cf6938a77f1aca83ef529dce96681efd1e6c5/ssl/ssl_lib.cc#L1861) groups in string
- Exposes BoringSSL method …
> Expose SSL_set1_groups to Efficiently Set Curves on SSL Session

- boring/src/pkey.rs
Had occasion to want these, hopefully relatively uncontroversial. I did see that there are two different ways of adapting the "measure once, output once" APIs: SslSession methods follow this approach, using an `&mut [u8]` argument and special-casing the empty case (though apparently that's done within BoringSSL itself); `EcPointRef::to_bytes`, by contrast, just calls the underlying BoringSSL API twice so it can return a `Vec<u8>`. Since the caller must already know something about the kind of key to expect success, I figured it was worth providing the more flexible slice-based API.
> Expose PKey::raw_{private,public}_key

- boring-sys/build/config.rs
- boring-sys/build/main.rs
This can make other doc builds like cargo-semver-checks faster.
Plus support for Cargo's `-j` (`NUM_JOBS`) and proper warnings.
> Don't compile binaries for docs.rs

- boring/src/hmac.rs
- boring/src/lib.rs
- boring/src/ssl/callbacks.rs
- boring/src/ssl/mod.rs
- boring/src/ssl/test/mod.rs
- boring/src/ssl/test/session_resumption.rs
- boring/src/symm.rs
Add a wrapper for the `SSL_CTX_set_tlsext_ticket_key_cb`, which allows consumers to configure the EVP_CIPHER_CTX and HMAC_CTX used for encrypting/decrypting session tickets.
See https://docs.openssl.org/1.0.2/man3/SSL_CTX_set_tlsext_ticket_key_cb/ for more details.
> Add set_ticket_key_callback (SSL_CTX_set_tlsext_ticket_key_cb)
